export const INIT_MOVIE_GENRES = 'INIT_MOVIE_GENRES';
export const INIT_MOVIE_GENRES_SUCCESS = 'INIT_MOVIE_GENRES_SUCCESS';
export const INIT_MOVIE_GENRES_FAILED = 'INIT_MOVIE_GENRES_FAILED';

export const START_FETCHING_SEARCH_RESULT = 'START_FETCHING_SEARCH_RESULT';
export const GET_SEARCH_RESULT = 'GET_SEARCH_RESULT';
export const SET_SEARCH_RESULT = 'SET_SEARCH_RESULT';
export const GET_SEARCH_RESULT_FAILED = 'GET_SEARCH_RESULT_FAILED';

export const START_FETCHING_SINGLE_MOVIE = 'START_FETCHING_SINGLE_MOVIE';
export const GET_SINGLE_MOVIE = 'GET_SINGLE_MOVIE';
export const GET_SINGLE_MOVIE_SUCCESS = 'GET_SINGLE_MOVIE_SUCCESS';
export const GET_SINGLE_MOVIE_FAILED = 'GET_SINGLE_MOVIE_FAILED';
